NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 120
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 60
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 13

NDefines.NDiplomacy.BASE_STAGE_COUP_DAILY_PP = 1000
NDefines.NDiplomacy.FRONT_IS_DANGEROUS = 0
NDefines.NDiplomacy.NOT_READY_FOR_WAR_BASE = 0
NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 80
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 30.0

--- Navy
NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.05 --- THIS IS FOR LAND CAS CAUSE PARADOX BUGGGGZ
NDefines.NNavy.ANTI_AIR_ATTACK_TO_AMOUNT = 0.001 --- THIS IS FOR LAND CAS CAUSE PARADOX BUGGGGZ
NDefines.NAir.DISRUPTION_FACTOR = 7.0  --- (4 -> 7)
NDefines.NNavy.ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE = 0.8 --- (0.2 -> 0.8)
NDefines.NNavy.SHIP_TO_FLEET_ANTI_AIR_RATIO = 0.01 --- (0.2 -> 0.01)
NDefines.NNavy.ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE = 0.8 --- (0.2 -> 0.8)
NDefines.NNavy.ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE = 0.04 --- (0.15 -> 0.04)
NDefines.NNavy.MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.8 --- (0.5 -> 0.8)
NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR    = 0.5 -- (0.25 -> 0.5)
NDefines.NNavy.BASE_GUN_COOLDOWNS = { -- doubled the cooldown of guns to make battles last longer and give ships time to escape
        2.0,    -- big guns
        8.0,    -- torpedos
        2.0,    -- small guns
}

NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 100
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_PENALTY = 0
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROLLED = -1000
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROL_DIFF = 0



NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0

NDefines.NCountry.ATTACHE_XP_SHARE = 0.1

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 400
NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 33.0
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.002
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 3
NDefines.NMilitary.EXPEDITIONARY_FIELD_EXPERIENCE_SCALE = 0.5
NDefines.NMilitary.LEND_LEASE_FIELD_EXPERIENCE_SCALE = 0.005

NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 35.0
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 35.0
NDefines.NMilitary.FIELD_MARSHAL_ARMY_BONUS_RATIO = 0.5
NDefines.NMilitary.FIELD_MARSHAL_XP_RATIO = 0.25
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.06
NDefines.NMilitary.CONSTANT_XP_RATIO_FOR_MULTIPLE_LEADERS_IN_SAME_COMBAT = 0.5
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.40

NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.5

NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0

NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0.90